### ISSUE TITLE
lwsm save doesn't work

### ISSUE THREAD

**Issue by 2Icoldinate** [johannesjo/linux-window-session-manager#47] opened 2019-10-07 11:35 UTC
## My Environment
* Version used: 3.0.1
* Operating Systtem and version: 18.04.3 LTS(ubuntu), gnome-shell(3.28.4) 
* Desktop Environment: 
* Node version: v12.10.0
 I followed guide provided by this [article](https://www.linuxuprising.com/2018/04/gnome-save-and-restore-running.html) article. 

 After installation, I wanted to save my session using 'lwsm save' command in gnome shell, I got below error instead.

` (node:13700) UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at Buffer.readUInt32LE (internal/buffer.js:206:5)
    at Buffer.unpack (/home/user/.npm-packages/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackbuffer.js:44:32)
    at /home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:589:45
    at step (/home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:63:23)
    at Object.next (/home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:44:53)
    at /home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:37:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:33:12)
    at _decodeProperty (/home/user/.npm-packages/lib/node_modules/linux-window-session-manager/dist/index.js:542:12)
(node:13700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

 I can't understand meaning of `RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError`. Is this for not enough ram?

**Comment by johannesjo** [comment] 2019-10-08 17:25
Meanwhile I suggest to use version v2.1.31 instead. The error should not occur there.

**Comment by 2Icoldinate** [comment] 2019-10-09 06:59
> Thanks for reporting. What applications do you have opened? Does it happen when you just have the terminal open?

I've only opened several chromium windows and several terminal windows.

**Comment by johannesjo** [comment] 2019-10-09 16:13
I released a new version (3.0.3) with additional debugging info. Would you be so kind to try with that version again and let me know what the output is? Unfortunately I'm not able to reproduce the error by myself.

**Comment by TheGoldenTeapot** [comment] 2019-10-10 17:22
Think I'm having a similar issue here. Was unsure whether to start a new thread or comment. Getting the below output when using lwsm save.

- Version used: 3.0.3
- Operating System and version: Ubuntu 19.04 (Ubuntu), gnome-shell(3.32.2)
- Node version: v12.11.1

`Error: Bad atom
    at ReadFixedRequest.callback (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23) {
  error: 5,
  seq: 4,
  message: 'Bad atom',
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 17
}
(node:21255) UnhandledPromiseRejectionWarning: Error: Bad atom
    at ReadFixedRequest.callback (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/gary/.nvm/versions/node/v12.11.1/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
(node:21255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21255) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by johannesjo** [comment] 2019-10-11 18:25
This hopefully should be fixed now. Thanks for all your help! Let me know if this persists for you or if you encounter any other issues.

**Closed** 2019-10-29 22:52 UTC

**Comment by masip85** [comment] 2019-11-22 09:23
Gitter hangs save process. Output info:
findDesktopFile cant find file; searched patterns []
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
(node:26701) UnhandledPromiseRejectionWarning: findDesktopFile cant find file; searched patterns
(node:26701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:26701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by johannesjo** [comment] 2019-11-23 17:30
@masip85 could you please post the contents of `~/.lwsm/config.json`. It looks like that it is missing the `DESKTOP_FILE_LOCATIONS` property.
